config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'
  root "blogs#index"
  resources :blogs
  resources :users, only: %i[ new create show ]
  resources :sessions, only: %i[ new create destroy ]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog.rb
# == Schema Information
#
# Table name: blogs
#
#  id         :bigint           not null, primary key
#  content    :text             not null
#  image      :text
#  title      :string(20)       not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
class Blog < ApplicationRecord
  include CommonModule
  mount_uploader :image, ImageUploader

  validates :title, presence: true, length: { maximum: 20 }
  validates :content, presence: true

end

app/models/concerns/common_module.rb
module CommonModule
  extend ActiveSupport::Concern

  included do
    scope :default, -> () { order(created_at: :desc)}
  end
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :bigint           not null, primary key
#  email           :string           not null
#  name            :string           not null
#  password_digest :string           not null
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#
# Indexes
#
#  index_users_on_email  (email) UNIQUE
#
class User < ApplicationRecord
  has_secure_password
  before_validation { email.downcase! }

  validates :name, presence: true, length: { maximum: 20 }
  validates :email, presence: true, length: { maximum: 255 }, uniqueness: true,
            format: { with: /\A[\w.!#$%&'*+\/=?^`{|}~-]+@[\w-]+\.[\w-]+\z/i }
  validates :password, presence: true, length: { minimum: 6 }, allow_nil: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include SessionsHelper
  add_flash_types :success, :info, :warning, :danger
  before_action :basic_auth unless Rails.env.test?
  before_action :login_required

  private

  def basic_auth
    authenticate_or_request_with_http_basic do |name, password|
      name == ENV["BASIC_AUTH_NAME"] && password == ENV["BASIC_AUTH_PASSWORD"]
    end
  end

  def login_required
    redirect_to new_session_path unless current_user
  end
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_action :set_blog, only: %i[show edit update destroy]

  # GET /blogs or /blogs.json
  def index
    @q = Blog.ransack(params[:q])
    @blogs = @q.result(distinct: true)
  end

  # GET /blogs/1 or /blogs/1.json
  def show; end

  # GET /blogs/new
  def new
    @blog = Blog.new
  end

  # GET /blogs/1/edit
  def edit; end

  # POST /blogs or /blogs.json
  def create
    @blog = Blog.new(blog_params)

    respond_to do |format|
      if @blog.save
        format.html { redirect_to blog_url(@blog), success: "Blog was successfully created." }
        format.json { render :show, status: :created, location: @blog }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /blogs/1 or /blogs/1.json
  def update
    respond_to do |format|
      if @blog.update(blog_params)
        format.html { redirect_to blog_url(@blog), success: "Blog was successfully updated." }
        format.json { render :show, status: :ok, location: @blog }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /blogs/1 or /blogs/1.json
  def destroy
    @blog.destroy

    respond_to do |format|
      format.html { redirect_to blogs_url, danger: "Blog was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def self.ransackable_attributes(auth_object = nil)
    %[title created_at]
  end

  def self.ransacable_associations(auth_object = nil)
    []
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_blog
    @blog = Blog.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def blog_params
    params.require(:blog).permit(:title, :content, :image, :image_cache)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :login_required

  def new; end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user&.authenticate(params[:session][:password])
      session[:user_id] = user.id
      redirect_to blogs_path, seccuess: "login success !"
    else
      flash.now[:danger] = "email and/or password wrong !"
      render :new
    end
  end

  def destroy
    session.delete(:user_id)
    redirect_to new_session_path, danger: "logout!"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :login_required, only: %i[new create]
  before_action :set_params, only: %i[show destroy]

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user
      redirect_to blogs_path, success: "success signup!"
    else
      render :new
    end
  end

  def show; end

  private
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_digest)
  end

  def set_params
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    current_user ||= User.find_by(id: session[:user_id])
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/blogs/_form.html.erb
<%= form_with(model: blog, local: true) do |form| %>
  <% if blog.errors.any? %>
    <div id="error_explanation alert alert-danger">
      <h2><%= pluralize(blog.errors.count, "error") %> prohibited this blog from being saved:</h2>

      <ul>
        <% blog.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field form-group">
    <%= form.label :title, class: "sr-only" %>
    <%= form.text_field :title, class: "form-control", required: true, autofocus: true, placeholder: t("activerecord.attributes.blog.title") %>
  </div>

  <div class="field form-group">
    <%= form.label :content, class: "sr-only" %>
    <%= form.text_area :content, class: "form-control", required: true, placeholder: t("activerecord.attributes.blog.content") %>
  </div>

  <div class="field form-group">
    <%= form.label :image, class: "sr-only" %>
    <%= form.file_field :image, class: "form-control", accept: ".png, .jpg, .jpeg, .gif" %>
    <%= form.hidden_field :image_cache %>
  </div>

  <div class="field form-group">
    <%= image_tag(blog.image.url) if blog.image&.url %>
  </div>

  <div class="actions">
    <%= form.submit nil, class: "btn btn-primary" %>
    <%= link_to t("views.button.back"), :back, class: "btn btn-warning" %>
  </div>
<% end %>

app/views/blogs/edit.html.erb
<h1>Editing Blog</h1>

<%= render 'form', blog: @blog %>

<%= link_to t("views.button.show"), @blog, class: "btn btn-info" %>

app/views/blogs/index.html.erb
<h1>Blogs</h1>

<%= search_form_for @q, class: "mb-5" do |f| %>
  <div class="row">
    <div class="form-group col">
      <%= f.label :title_cont, "#{Blog.human_attribute_name(:title)} or #{Blog.human_attribute_name(:content)}", class: "sr-only" %>
      <%= f.search_field :title_or_content_cont, class: "form-control", placeholder: "#{Blog.human_attribute_name(:title)} or #{Blog.human_attribute_name(:content)}" %>
    </div>
    <div class="form-group col">
      <%= f.label :created_at_gteq, Blog.human_attribute_name(:created_at), class: "sr-only" %>
      <%= f.datetime_field :created_at_gteq, class: "form-control", placeholder: Blog.human_attribute_name(:created_at) %>
    </div>
    <div class="actions col">
      <%= f.submit class: "btn btn-outline-primary" %>
      <%= link_to t("views.button.clear"), request.path, class: "btn btn-outline-warning" %>
    </div>
  </div>
<% end %>

<%= link_to t("views.button.new"), new_blog_path, class: "btn btn-primary" %>
<table class="table blogs-table">
  <thead>
    <tr>
      <th><%= sort_link @q, :title, [:title, "created_at: :desc"] %></th>
      <th><%= Blog.human_attribute_name(:content) %></th>
      <th><%= Blog.human_attribute_name(:image) %></th>
      <th><%= sort_link @q, :created_at, default_order: :desc %></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @blogs.each do |blog| %>
      <tr>
        <td><%= blog.title %></td>
        <td><%= blog.content %></td>
        <td><%= image_tag(blog.image.url, width: "150px", height: "auto") if blog.image&.url %></td>
        <td><%= time_ago_in_words(blog.created_at) %></td>
        <td>
          <%= link_to t("views.button.show"), blog, class: "btn btn-outline-info btn-block" %>
          <%= link_to t("views.button.edit"), edit_blog_path(blog), class: "btn btn-outline-success btn-block" %>
          <%= link_to t("views.button.destroy"), blog, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-outline-danger btn-block" %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/blogs/new.html.erb
<h1>New Blog</h1>

<%= render 'form', blog: @blog %>

app/views/blogs/show.html.erb
<table class="table">
  <tr>
    <th scope="row"><%= t("activerecord.attributes.blog.title")%></th>
    <td><%= simple_format(@blog.title) %></td>
  </tr>
  <tr>
    <th scope="row"><%= t("activerecord.attributes.blog.content")%></th>
    <td><%= simple_format(@blog.content) %></td>
  </tr>
  <tr>
    <th scope="row"><%= t("activerecord.attributes.blog.image")%></th>
    <td><%= image_tag(@blog.image.url) if @blog.image&.url %></td>
  </tr>
</table>
<%= link_to t("views.button.edit"), edit_blog_path(@blog), class: "btn btn-success" %> |
<%= link_to t("views.button.destroy"), blog_path(@blog), class: "btn btn-danger", method: :delete, data: {confirm: 'Are you sure?'} %> |
<%= link_to t("views.button.back"), :back, class: "btn btn-warning" %> |
<%= link_to t("views.index"), blogs_path, class: "btn btn-dark" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AwsBlogApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header class=header>
      <div class="header-logo">
        <%= link_to "Blogs", blogs_path, class: "header-logo"%>
      </div>
      <ul class="header-list">
        <% if current_user %>
          <li><%= link_to current_user.name, user_path(current_user)%></li>
          <li><%= link_to t("views.button.logout"), session_path(current_user), method: :delete %></li>
        <% else %>
          <li><%= link_to t("views.button.signup"), new_user_path %></li>
          <li><%= link_to t("views.button.login"), new_session_path %></li>
        <% end %>
      </ul>
    </header>
    <main>
      <% flash.each do |key, message| %>
        <%= content_tag :div, message, class: "alert alert-#{key}" %>
      <% end %>
      <div class="container">
        <%= yield %>
      </div>
    </main>
  </body>
</html>

app/views/users/new.html.erb
<% provide(:title, "signup") %>

<%= form_with(model: @user, local: true) do |form| %>
  <% if @user.errors.any? %>
    <div class="alert alert-danger">
      <h2><%= @user.errors.count %>件のエラーがあります。</h2>
      <ul>
        <% @user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="form-group">
    <%= form.label :name, class: "sr-only" %>
    <%= form.text_field :name, class: "form-control", required: true, autofocus: true, placeholder: User.human_attribute_name(:name) %>
  </div>
  <div class="form-group">
    <%= form.label :email, class: "sr-only" %>
    <%= form.email_field :email, class: "form-control", required: true, placeholder: User.human_attribute_name(:email) %>
  </div>
  <div class="form-group">
    <%= form.label :password, class: "sr-only" %>
    <%= form.password_field :password, class: "form-control", required: true, placeholder: User.human_attribute_name(:password) %>
  </div>
  <div class="form-group">
    <%= form.label :password_confirmation, class: "sr-only" %>
    <%= form.password_field :password_confirmation, class: "form-control", required: true, placeholder: User.human_attribute_name(:password_confirmation) %>
  </div>
  <div class="form-group">
    <%= form.submit nil, class: "btn btn-primary" %>
  </div>
<% end %>

app/views/users/show.html.erb
<% provide(:title, "show") %>

<table class="table">
  <tr>
    <th><%= User.human_attribute_name(:name) %></th>
    <td><%= @user.name %></td>
  </tr>
  <tr>
    <th><%= User.human_attribute_name(:email) %></th>
    <td><%= @user.email %></td>
  </tr>
</table>